services:
  pluto-producer:
    build:
      context: ./apps/pluto/pluto-producer
      dockerfile: Dockerfile
    container_name: pluto-producer
    restart: always
    volumes:
      - ./logs/pluto/pluto-producer:/app/logs
      - ./libs/py:/app/libs/py
    environment:
      - PYTHONPATH=/app:/app/libs/py
      - PYTHONUNBUFFERED=1
      - LOG_PATH=/app/logs
      - IPADDR=192.168.1.50
    profiles:
      - pluto-producer
      - pluto
  pluto-tc-producer:
    build:
      context: ./apps/pluto/pluto-tc-producer
      dockerfile: Dockerfile
    container_name: pluto-tc-producer
    restart: always
    volumes:
      - ./logs/pluto/pluto-tc-producer:/app/logs
      - ./libs/py:/app/libs/py
    environment:
      - PYTHONPATH=/app:/app/libs/py
      - PYTHONUNBUFFERED=1
      - LOG_PATH=/app/logs
      - IPADDR=192.168.1.33
    profiles:
      - pluto-tc-producer
      - pluto
    network_mode: "host"
